# Generated by Django 3.2.5 on 2021-07-13 03:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import main.models
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.department')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='main.sector')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.CharField(default=main.models.random_string, max_length=30, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('birth_date', models.DateField()),
                ('blood_type', models.CharField(choices=[('o+', 'O+'), ('o-', 'O-'), ('a+', 'A+'), ('a-', 'A-'), ('b+', 'B+'), ('b-', 'B-'), ('ab+', 'AB+'), ('ab-', 'AB-')], default='O+', max_length=3)),
                ('occupation', models.CharField(max_length=100)),
                ('e_type', models.CharField(choices=[('pns', 'PNS'), ('p3k', 'P3K'), ('honorer', 'HONORER')], default='pns', max_length=9)),
                ('echelon', models.CharField(blank=True, choices=[('2a', 'IIA'), ('2b', 'IIB'), ('3a', 'IIIA'), ('3b', 'IIIB'), ('4a', 'IVA'), ('4b', 'IVB'), ('5a', 'VA'), ('5b', 'VB'), ('non', 'Non Eselon'), ('fungsional', 'Fungsional')], default='2a', max_length=15, null=True)),
                ('class_rank', models.CharField(blank=True, choices=[('1a', 'IA'), ('1b', 'IB'), ('1c', 'IC'), ('1d', 'ID'), ('2a', 'IIA'), ('2b', 'IIB'), ('2c', 'IIC'), ('2d', 'IID'), ('3a', 'IIIA'), ('3b', 'IIIB'), ('3c', 'IIIC'), ('3d', 'IIID'), ('4a', 'IVA'), ('4b', 'IVB'), ('4c', 'IVC'), ('4d', 'IVD')], default='1a', max_length=5, null=True)),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.department')),
                ('sector', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.sector')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('finish_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('information', models.TextField()),
                ('c_status', models.CharField(choices=[('ct1', 'Diproses'), ('ct2', 'Diambil'), ('ct3', 'Selesai')], default='ct1', max_length=10)),
                ('owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='main.employee')),
                ('taker', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taker', to='main.employee')),
            ],
        ),
    ]
