# Generated by Django 3.2.5 on 2021-07-13 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='abbreviation',
            field=models.CharField(default=None, max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
