# Generated by Django 3.2.5 on 2021-07-09 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='class_rank',
            field=models.CharField(blank=True, choices=[('1a', 'IA'), ('1b', 'IB'), ('1c', 'IC'), ('1d', 'ID'), ('2a', 'IIA'), ('2b', 'IIB'), ('2c', 'IIC'), ('2d', 'IID'), ('3a', 'IIIA'), ('3b', 'IIIB'), ('3c', 'IIIC'), ('3d', 'IIID'), ('4a', 'IVA'), ('4b', 'IVB'), ('4c', 'IVC'), ('4d', 'IVD')], default='1a', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='echelon',
            field=models.CharField(blank=True, choices=[('2a', 'IIA'), ('2b', 'IIB'), ('3a', 'IIIA'), ('3b', 'IIIB'), ('4a', 'IVA'), ('4b', 'IVB'), ('5a', 'VA'), ('5b', 'VB'), ('non', 'Non Eselon'), ('fungsional', 'Fungsional')], default='2a', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='eid',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('pns', 'PNS'), ('p3k', 'P3K'), ('honorer', 'HONORER')], default='pns', max_length=9),
        ),
        migrations.AlterField(
            model_name='employee',
            name='blood_type',
            field=models.CharField(choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], default='O+', max_length=3),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
