# Generated by Django 3.2.5 on 2021-07-09 13:41

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210709_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='eid',
            field=models.CharField(blank=True, default=main.models.random_string, max_length=30, unique=True),
        ),
    ]
